import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import dotenv from "dotenv";

// Load environment variables from .env
dotenv.config();

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin.
*/`;

const isProd = process.argv[2] === "production";

// Default copy destination
const defaultDest = "C:\\Users\\Yhx06\\Documents\\Obsidian Vault\\.obsidian\\plugins\\obsidian-scriptorium";
const targetDir = process.env.OBSIDIAN_PLUGIN_DIR || defaultDest;
const targetDirs = [targetDir];
const activeVaultDest = "d:\\Yhx06\\Documents\\仙术工坊——项目集\\.obsidian\\plugins\\obsidian-scriptorium";
if (!targetDirs.includes(activeVaultDest)) {
  targetDirs.push(activeVaultDest);
}

const styleSources = [
  "styles.css",
  "src/styles/tokens.css",
  "src/styles/shell.css",
  "src/styles/navigator.css",
  "src/styles/log-dock.css",
  "src/styles/native-overrides.css",
];

const copyManifestAndStyles = () => {
  try {
    const mainSource = path.join(targetDir, "main.js");
    const hasMainSource = fs.existsSync(mainSource);

    for (const dir of targetDirs) {
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      
      // Copy manifest.json
      fs.copyFileSync("manifest.json", path.join(dir, "manifest.json"));
      console.log(`Copied manifest.json to ${dir}`);
      
      // Copy main.js from targetDir if it exists and dir is secondary
      if (dir !== targetDir && hasMainSource) {
        fs.copyFileSync(mainSource, path.join(dir, "main.js"));
        console.log(`Copied main.js to ${dir}`);
      }
      
      // Source is authoritative: merge styles
      const mergedStyles = styleSources
        .filter((source) => fs.existsSync(source))
        .map((source) => `/* source: ${source} */\n${fs.readFileSync(source, "utf8")}`)
        .join("\n\n");
      fs.writeFileSync(path.join(dir, "styles.css"), mergedStyles, "utf8");
      console.log(`Built styles.css from ${styleSources.length} source files into ${dir}`);
    }
  } catch (err) {
    console.error("Error during copying assets:", err);
  }
};

const buildContext = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    "child_process",
    "fs",
    "path",
    "os"
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: isProd ? false : "inline",
  treeShaking: true,
  outfile: path.join(targetDir, "main.js"),
});

if (isProd) {
  await buildContext.rebuild();
  copyManifestAndStyles();
  process.exit(0);
} else {
  copyManifestAndStyles();
  await buildContext.watch();
  console.log("Watching for changes...");
}
